export const DREAMS = [
  { emoji: "🇹🇷", title: "Visit Turkey together" },
  { emoji: "🇻🇳", title: "Visit Vietnam together" },
  { emoji: "🎮", title: "Win a Valorant tournament" },
  { emoji: "🌅", title: "Watch a sunset on a beach" },
  { emoji: "🏠", title: "Build our own place" },
  { emoji: "🐱", title: "Get a pet together" },
  { emoji: "🎵", title: "Go to a concert together" },
  { emoji: "📸", title: "Have a proper photoshoot" },
  { emoji: "🌌", title: "Stargaze somewhere remote" },
  { emoji: "🎄", title: "Spend Christmas together" },
  { emoji: "🍳", title: "Cook a meal together" },
  { emoji: "🚗", title: "Take a spontaneous road trip" },
  { emoji: "✈️", title: "Travel somewhere new every year" },
  { emoji: "📖", title: "Write our love story" },
  { emoji: "🏕️", title: "Camp under the stars" },
  { emoji: "💃", title: "Learn to dance together" },
  { emoji: "💌", title: "Handwritten letters, always" },
  { emoji: "🌧️", title: "Kiss in the rain (mandatory)" },
  { emoji: "🥐", title: "Lazy Sunday breakfast in bed" },
  { emoji: "💍", title: "Forever and always" },
];
